"""PostgreSQL schema helpers shared by migration tooling and tests."""
from __future__ import annotations

import re


def postgres_schema(sqlite_schema: str) -> str:
    schema = re.sub(r"(?im)^PRAGMA[^;]+;\s*", "", sqlite_schema)
    return schema.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
