"""PostgreSQL schema helpers shared by migration tooling and tests."""
from __future__ import annotations

import re
from typing import Any, Iterator

_IDENTITY_TABLES = {
    "users", "devices", "conversations", "messages", "tasks", "approvals", "auth_tokens",
    "metric_events", "audit_log", "memory", "agent_files", "agent_jobs", "notifications",
    "conversation_jobs", "ops_agents", "ops_incidents", "ops_incident_events",
    "ops_agent_assignments", "ops_agent_messages", "ops_action_proposals", "ops_approvals",
    "ops_notifications", "ops_evidence", "ops_code_changes", "ops_check_runs",
    "ops_deployments", "ops_agent_usage",
}


def postgres_schema(sqlite_schema: str) -> str:
    schema = re.sub(r"(?im)^PRAGMA[^;]+;\s*", "", sqlite_schema)
    schema = schema.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    # SQLite REAL is an IEEE-754 double; PostgreSQL REAL is only 4 bytes.
    return re.sub(r"\bREAL\b", "DOUBLE PRECISION", schema)


def translate_qmarks(query: str) -> str:
    """Translate sqlite placeholders without touching question marks in SQL strings."""
    result: list[str] = []
    quoted = False
    index = 0
    while index < len(query):
        char = query[index]
        if char == "'":
            result.append(char)
            if quoted and index + 1 < len(query) and query[index + 1] == "'":
                result.append("'")
                index += 2
                continue
            quoted = not quoted
        elif char == "?" and not quoted:
            result.append("%s")
        else:
            result.append(char)
        index += 1
    translated = "".join(result)
    translated = re.sub(r"(?i)datetime\(\s*'now'\s*\)", "CURRENT_TIMESTAMP", translated)
    translated = re.sub(
        r"(?i)datetime\(\s*'now'\s*,\s*'-(\d+)\s+(hours?|minutes?|days?)'\s*\)",
        lambda match: f"(CURRENT_TIMESTAMP - INTERVAL '{match.group(1)} {match.group(2)}')",
        translated,
    )
    translated = re.sub(
        r"(?i)datetime\(\s*'now'\s*,\s*'start of day'\s*\)",
        "date_trunc('day', CURRENT_TIMESTAMP)",
        translated,
    )
    return translated


def escape_literal_percents(query: str) -> str:
    result: list[str] = []
    quoted = False
    index = 0
    while index < len(query):
        char = query[index]
        if char == "'":
            result.append(char)
            if quoted and index + 1 < len(query) and query[index + 1] == "'":
                result.append("'")
                index += 2
                continue
            quoted = not quoted
        elif char == "%" and quoted:
            result.append("%%")
        else:
            result.append(char)
        index += 1
    return "".join(result)


class PostgresCursor:
    def __init__(self, cursor, returned_row=None, lastrowid=None):
        self._cursor = cursor
        self._returned_row = returned_row
        self.lastrowid = lastrowid

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount

    def fetchone(self):
        if self._returned_row is not None:
            row, self._returned_row = self._returned_row, None
            return row
        return self._cursor.fetchone()

    def fetchall(self):
        rows = self._cursor.fetchall()
        if self._returned_row is not None:
            rows.insert(0, self._returned_row)
            self._returned_row = None
        return rows

    def __iter__(self) -> Iterator[Any]:
        if self._returned_row is not None:
            yield self.fetchone()
        yield from self._cursor


class PostgresConnection:
    """Small sqlite-compatible facade used while routes migrate incrementally."""
    def __init__(self, connection):
        self._connection = connection

    def execute(self, query: str, params=()) -> PostgresCursor:
        if re.match(r"\s*PRAGMA\b", query, re.I):
            # Compatibility for SQLite tuning probes in shared diagnostics.
            return self.execute("SELECT 1")
        translated = translate_qmarks(query)
        if params:
            translated = escape_literal_percents(translated)
        match = re.match(r"\s*INSERT\s+(?:OR\s+IGNORE\s+)?INTO\s+([\w\"]+)", query, re.I)
        if re.match(r"\s*INSERT\s+OR\s+IGNORE", query, re.I):
            translated = re.sub(r"(?i)^\s*INSERT\s+OR\s+IGNORE", "INSERT", translated, count=1)
            translated = translated.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
        table = match.group(1).strip('"') if match else None
        wants_id = bool(table in _IDENTITY_TABLES and not re.search(r"\bRETURNING\b", translated, re.I))
        if wants_id:
            translated = translated.rstrip().rstrip(";") + " RETURNING id"
        cursor = self._connection.cursor()
        cursor.execute(translated, params)
        if wants_id:
            row = cursor.fetchone()
            return PostgresCursor(cursor, lastrowid=row["id"] if row else None)
        return PostgresCursor(cursor)

    def executescript(self, script: str) -> None:
        self._connection.execute(script)

    def commit(self) -> None:
        self._connection.commit()

    def rollback(self) -> None:
        self._connection.rollback()

    def close(self) -> None:
        self._connection.close()
