from rapiin.database import SCHEMA


def test_postgres_schema_removes_sqlite_only_constructs():
    from rapiin.postgres_support import postgres_schema

    schema = postgres_schema(SCHEMA)
    assert "PRAGMA" not in schema
    assert "AUTOINCREMENT" not in schema
    assert "GENERATED BY DEFAULT AS IDENTITY" in schema
    assert "DOUBLE PRECISION" in schema


def test_qmark_translation_preserves_string_literals():
    from rapiin.postgres_support import escape_literal_percents, translate_qmarks

    assert translate_qmarks("SELECT * FROM users WHERE id=? AND note='why?' AND email=?") == (
        "SELECT * FROM users WHERE id=%s AND note='why?' AND email=%s"
    )
    assert translate_qmarks("SELECT '?' AS mark, ? AS value") == "SELECT '?' AS mark, %s AS value"
    assert translate_qmarks("SELECT datetime('now')") == "SELECT CURRENT_TIMESTAMP"
    assert escape_literal_percents("SELECT * FROM t WHERE name LIKE '%safe%' AND id=%s") == (
        "SELECT * FROM t WHERE name LIKE '%%safe%%' AND id=%s"
    )
