from beresin.database import SCHEMA


def test_postgres_schema_removes_sqlite_only_constructs():
    from beresin.postgres_support import postgres_schema

    schema = postgres_schema(SCHEMA)
    assert "PRAGMA" not in schema
    assert "AUTOINCREMENT" not in schema
    assert "GENERATED BY DEFAULT AS IDENTITY" in schema
